version: '2.0'

services:
    uoc-pg:
        image: camptocamp/postgres:9.6
        container_name: uoc-pg
        volumes:
            - ./postgresqlData:/var/lib/postgresql/data
            - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
        networks:
            - uoc-network
        env_file:
            - ./.env.production

    uoc-cdn:
        container_name: uoc-cdn
        build:
            context: ./
            dockerfile: Dockerfile.cdn
        volumes:
            - ./public/cdn:/usr/src/app/public/cdn
        ports:
            - '81:80'
        env_file:
            - ./.env.production

    uoc-next:
        container_name: uoc-next
        build:
            context: ./
            dockerfile: Dockerfile.next
        volumes:
            - ./uoc-next-logs:/usr/src/app/logs
            - ./public/cdn:/usr/src/app/public/cdn
        networks:
            - uoc-network
        ports:
            - '80:80'
        depends_on:
            - uoc-pg
        env_file:
            - ./.env.production

networks:
    uoc-network:
