services:
    uoc-next:
        container_name: uoc-next
        build:
            context: ./
            dockerfile: Dockerfile.next
        volumes:
            - ./cdn:/usr/src/app/cdn
        networks:
            - uoc-network
        env_file:
            - ./.env.production

    uoc-nginx:
        image: nginx:1.21.6
        build:
            context: ./
            dockerfile: Dockerfile.nginx
        container_name: uoc-nginx
        restart: unless-stopped
        ports:
            - '80:80'
            - '443:443'
        networks:
            - uoc-network
        volumes:
            - ./certbot/conf:/etc/letsencrypt
            - ./certbot/www:/var/www/certbot
            - ./cdn:/var/www/cdn
            - ./baltijas_autoserviss:/var/www/baltijas_autoserviss

    mailserver:
        image: docker.io/mailserver/docker-mailserver:12.1.0
        container_name: mailserver
        # If the FQDN for your mail-server is only two labels (eg: example.com),
        # you can assign this entirely to `hostname` and remove `domainname`.
        hostname: mail.uoc.lv
        # domainname: mail.uoc.lv
        env_file: mailserver.env
        # More information about the mail-server ports:
        # https://docker-mailserver.github.io/docker-mailserver/edge/config/security/understanding-the-ports/
        # To avoid conflicts with yaml base-60 float, DO NOT remove the quotation marks.
        ports:
            - '25:25' # SMTP  (explicit TLS => STARTTLS)
            - '143:143' # IMAP4 (explicit TLS => STARTTLS)
            - '465:465' # ESMTP (implicit TLS)
            - '587:587' # ESMTP (explicit TLS => STARTTLS)
            - '993:993' # IMAP4 (implicit TLS)
        volumes:
            - ./mailserver/mail/:/mailserver/mail/
            - ./mailserver/mail-state/:/mailserver/mail-state/
            - ./mailserver/logs/:/mailserver/log/
            - ./mailserver/config/:/tmp/docker-mailserver/
            # - ./etc/localtime:/etc/localtime:ro
            - ./certbot/conf:/etc/letsencrypt
        restart: always
        stop_grace_period: 1m
        cap_add:
            - NET_ADMIN
        healthcheck:
            test: "ss --listening --tcp | grep -P 'LISTEN.+:smtp' || exit 1"
            timeout: 3s
            retries: 0

    uoc-shop-mysql:
        image: mysql:5.6.33
        container_name: uoc-shop-mysql
        volumes:
            - ./mysqlData:/var/lib/mysql
        networks:
            - uoc-network
        env_file:
            - ./.env.production

    uoc-shop:
        image:  wordpress:6.0.1-php7.4-apache #wordpress:5.4.1-php7.2-apache
        container_name: uoc-shop
        volumes:
            - ./shop-wordpress-html:/var/www/html
        networks:
            - uoc-network
        restart: unless-stopped
        depends_on:
            - uoc-shop-mysql
        env_file:
            - ./.env.production

    uoc-certbot:
        container_name: uoc-certbot
        image: certbot/certbot:v1.32.2
        depends_on:
            - uoc-nginx
        volumes:
            - ./certbot/conf:/etc/letsencrypt
            - ./certbot/www:/var/www/certbot
        command: certonly --webroot -w /var/www/certbot --force-renewal --email mjasnikovs@gmail.com -d uoc.lv --agree-tos

networks:
    uoc-network:
