version: '2.0'

services:
    uoc-pg:
        image: postgres:14.3-alpine3.16
        container_name: uoc-pg
        volumes:
            - ./postgresqlData:/var/lib/postgresql/data
            - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
        networks:
            - uoc-network
        env_file:
            - ./.env.production

    uoc-next:
        container_name: uoc-next
        build:
            context: ./
            dockerfile: Dockerfile.next
        volumes:
            - ./logs:/usr/src/app/logs
            - ./public/cdn:/usr/src/app/public/cdn
        networks:
            - uoc-network
        depends_on:
            - uoc-pg
        env_file:
            - ./.env.production

    uoc-nginx:
        image: nginx:1.21.6
        build:
            context: ./
            dockerfile: Dockerfile.nginx
        container_name: uoc-nginx
        restart: unless-stopped
        ports:
            - "80:80"
            - "443:443"  
        networks:
            - uoc-network
        volumes:
            - ./certbot/conf:/etc/letsencrypt
            - ./certbot/www:/var/www/certbot
            - ./public/cdn:/var/www/cdn

    certbot:
        container_name: uoc-certbot
        image: certbot/certbot:v1.28.0
        depends_on:
            - uoc-nginx
        volumes:
            - ./certbot/conf:/etc/letsencrypt
            - ./certbot/www:/var/www/certbot
        # command: certonly --webroot -w /var/www/certbot --force-renewal --email mjasnikovs@gmail.com -d mx5.lv --agree-tos

networks:
    uoc-network:
