version: '2.0'

services:
    uoc-cdn:
        container_name: uoc-cdn
        build:
            context: ./
            dockerfile: Dockerfile.cdn
        volumes:
            - ./cdn:/usr/src/app/public/cdn
        networks:
            - uoc-network
        ports:
            - '3001:80'
        env_file:
            - ./.env.development

networks:
    uoc-network:
